sudo: false
language: node_js
matrix:
    fast_finish: true
node_js:
    - 0.10
    - 0.12
services:
    - couchdb
env:
    global:
        - NODE_ENV=test

before_install:
    - export INDEXES_PATH=/home/travis/build/indexes
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install # data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log -e forever-ds-err.log build/server.js
    - ps aux | grep server.js
    - sleep 5
    - cat forever-ds.log
    - curl http://localhost:9101/
    - coffee commands.coffee test-install photos
    - cd ..
    - export NAME=photos
    - export TOKEN=apptoken
    - mkdir -p build/client/public/img/
    - cp client/app/assets/img/cozy-logo.png build/client/public/img/

script:
    - npm test

after_failure:
    - pwd
    - ps aux | grep server.js
    - netstat -lntp
    - cat /home/travis/build/cozy/cozy-photos/cozy-data-system/forever-ds.log
    - cat /home/travis/build/cozy/cozy-photos/cozy-data-system/forever-ds-err.log
    - curl -v http://localhost:9101/
