language: node_js
node_js:
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install # data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - ps aux | grep server.js
    - sleep 5
    - cat forever-ds.log
    - sudo netstat -plunt
    - curl http://localhost:9101/
    - coffee commands.coffee test-install photos
    - cd ..
    - export NAME=photos
    - export TOKEN=apptoken

